#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: tool/build_platform.sh Android|Linux|Windows debug|profile|release" >&2
  exit 2
fi

proofray_target="$1"
proofray_mode="$2"
proofray_app_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
proofray_flutter_bin="${PROOFRAY_FLUTTER_BIN:-flutter}"

case "$proofray_target" in
  Android|Linux|Windows) ;;
  *) echo "unsupported v1 target: $proofray_target" >&2; exit 2 ;;
esac
case "$proofray_mode" in
  debug|profile|release) ;;
  *) echo "unsupported build mode: $proofray_mode" >&2; exit 2 ;;
esac

proofray_python_app="$proofray_app_dir/build/python-app/$proofray_target"
proofray_site_packages="$proofray_app_dir/build/site-packages/$proofray_target"
if [[ ! -d "$proofray_python_app" || ! -d "$proofray_site_packages" ]]; then
  echo "package Python for $proofray_target before building" >&2
  exit 3
fi

export SERIOUS_PYTHON_VERSION=3.12
export SERIOUS_PYTHON_APP="$proofray_python_app"
export SERIOUS_PYTHON_SITE_PACKAGES="$proofray_site_packages"

# dart_bridge (the native library behind SeriousPython.run(), see
# https://github.com/flet-dev/dart-bridge) is dlopen'd by Dart FFI, which
# defaults to RTLD_LOCAL. Its own NEEDED entry on libpython3.so (and that
# library's own NEEDED entry on the real libpython3.12.so.1.0) therefore
# loads the whole Python runtime into local, not global, ELF scope. Compiled
# C-extension wheels like NumPy never link against any libpython.so
# directly (standard manylinux/auditwheel convention) -- they rely on the
# host process having already made those symbols (e.g. PyObject_SelfIter)
# globally visible before the extension itself gets dlopen'd by Python's
# own import machinery. Confirmed by reproduction: without this, the
# embedded core crashes on the very first `import numpy` with
# `undefined symbol: PyObject_SelfIter`, and the app permanently shows
# "LOCAL CORE UNAVAILABLE" (the crash is silent from the Flutter side --
# only the Python subprocess's own stderr shows it). LD_PRELOAD-ing the
# full libpython .so is the standard fix for this class of problem: it
# forces global scope at process startup, before any later dlopen call.
# This is Linux-specific -- Windows DLL imports are resolved per-module
# from an explicit import table (numpy's own .pyd there DOES import
# python312.dll directly), so this exact failure mode doesn't apply there.
proofray_linux_preload_wrap() {
  local mode="$1"
  local bundle="$proofray_app_dir/build/linux/x64/$mode/bundle"
  local real_binary="$bundle/proofray_app.bin"
  local libpython
  libpython="$(find "$bundle/lib" -maxdepth 1 -name 'libpython3.[0-9]*.so.*' -print -quit)"
  if [[ -z "$libpython" ]]; then
    echo "libpython3.so not found under $bundle/lib; cannot wrap for global symbol scope" >&2
    exit 4
  fi
  mv -f "$bundle/proofray_app" "$real_binary"
  cat > "$bundle/proofray_app" <<WRAPPER
#!/bin/sh
# Generated by tool/build_platform.sh -- see its own comment for why this
# exists. Do not launch proofray_app.bin directly; NumPy (and any other
# compiled C-extension dependency) will crash on import without this.
here="\$(CDPATH= cd -- "\$(dirname -- "\$0")" && pwd)"
export LD_PRELOAD="\$here/lib/$(basename "$libpython")\${LD_PRELOAD:+:\$LD_PRELOAD}"
exec "\$here/proofray_app.bin" "\$@"
WRAPPER
  chmod +x "$bundle/proofray_app"
}

cd "$proofray_app_dir"
case "$proofray_target" in
  Linux)
    "$proofray_flutter_bin" build linux "--$proofray_mode"
    proofray_linux_preload_wrap "$proofray_mode"
    ;;
  Windows)
    "$proofray_flutter_bin" build windows "--$proofray_mode"
    ;;
  Android)
    "$proofray_flutter_bin" build apk "--$proofray_mode" \
      --target-platform android-arm64
    ;;
esac
